app/app/main/views.py
from flask import (
    Blueprint,
    render_template,
    redirect,
    url_for,
    jsonify,
    session,
    request,
)
from flask import current_app as app
from flask import abort
from flask_login import current_user, login_user, logout_user, login_required
from app.main.forms import Signup, TimetableOptions, BookingForm, CancelForm
from app import db, bcrypt
from app.models import User, Activity, Facility, Booking
from datetime import datetime, timedelta, date, time
from sqlalchemy import extract, and_
from app.user.views import booking_email_confirmation
import os
import html
import decimal
import re
from app.pay.payments import create_pending_payment
from app.main.callbacks import create_booking as booking_callback
from app.pay.payments import redirections as pay_redirects
from .helpers import get_activity_price


# Blueprint Configuration
main_bp = Blueprint(
    "main_bp", __name__, template_folder="templates", static_folder="static"
)


@main_bp.route("/index", methods=["GET"])
@main_bp.route("/", methods=["GET"])
def index():
    """Homepage route."""
    images = os.listdir(os.path.join(app.static_folder, "CarouselImages"))
    return render_template("index.html", images=images)


@main_bp.route("/facility/<facility_choice>")
def facility(facility_choice):
    facility_name_list = re.findall("[A-Z][^A-Z]*", facility_choice)
    facility_name = ""
    for i in facility_name_list:
        facility_name = facility_name + i + " "
    facility_name = facility_name.strip()
    if facility_name == "Squash Courts":
        facility_name = "Squash Court 1"
    if db.session.query(Facility.name).filter_by(name=facility_name).scalar() is None:
        return abort(404)
    imageFolder = facility_choice + "Images"
    folder = os.listdir(os.path.join(app.static_folder, imageFolder))

    facility_id = Facility.query.filter_by(name=facility_name).first().id
    activities = (
        Activity.query.filter_by(facility_id=facility_id).group_by(Activity.name).all()
    )
    for i in range(0, len(activities)):
        activities[i] = activities[i].name

    activity_list = ",".join(activities)

    return render_template(
        "facility.html",
        folder=folder,
        folder_name=imageFolder,
        facility_name=facility_name,
        activity_list=activity_list,
    )


@main_bp.route("/signup", methods=["GET", "POST"])
def signup():
    signup_form = Signup()
    if signup_form.validate_on_submit():
        create_user(
            signup_form.first_name.data,
            signup_form.last_name.data,
            signup_form.email.data,
            signup_form.password.data,
            signup_form.emergency_number.data,
            signup_form.dob.data,
        )
        return redirect(url_for("main_bp.index"))
    return render_template("signup.html", form=signup_form)


def create_user(first_name, last_name, email, password, emergency_num, dob):
    # create new user, hash password and add to the database
    password_hash = bcrypt.generate_password_hash(password).decode("utf-8")
    new_user = User(
        first_name=first_name,
        last_name=last_name,
        email=email,
        password=password_hash,
        emergency_number=emergency_num,
        dob=dob,
        user_type=3,
    )
    db.session.add(new_user)
    db.session.commit()


# Main code ran when on timetable page


@main_bp.route("/timetable", methods=["GET", "POST"])
def timetable():

    # Sets current day and creates list of days in upcoming month

    today = datetime.now()
    upcoming_month = []
    times = [
        (900, "9:00"),
        (1000, "10:00"),
        (1100, "11:00"),
        (1200, "12:00"),
        (1300, "13:00"),
        (1400, "14:00"),
        (1500, "15:00"),
        (1600, "16:00"),
        (1700, "17:00"),
    ]

    for i in range(0, 28):
        upcoming_month.append(today + timedelta(days=i))

    # Creates instance of the timetable options form
    # Sets the range of choices for start time, end time, and start date

    options = TimetableOptions()

    options.start_time.choices = times[0:8]
    options.end_time.choices = times[1:9]

    options.start_date.choices = [
        (day.strftime("%x"), day.strftime("%d/%m/%Y")) for day in upcoming_month
    ]

    # After submitting the timetable options, generate timetable function is run

    if options.validate_on_submit():
        return generateTimetable(options)

    # Loads the html page, using the options form created

    facilities = Facility.query.all()

    return render_template("timetable.html", form=options, facilities=facilities)


def generateTimetable(options):

    # Reads completed form data
    start_time = options.start_time.data
    end_time = options.end_time.data
    selected_day = datetime.strptime(options.start_date.data, "%x")
    activities = [[], [], [], [], [], [], []]
    next_week = []

    facilities = options.facility.data

    if len(facilities) > 0:
        for i in range(0, len(facilities)):
            facilities[i] = Facility.query.filter_by(name=facilities[i]).first().id

    times = [
        (900, "9:00"),
        (1000, "10:00"),
        (1100, "11:00"),
        (1200, "12:00"),
        (1300, "13:00"),
        (1400, "14:00"),
        (1500, "15:00"),
        (1600, "16:00"),
        (1700, "17:00"),
    ]

    # Finds index position of start and end time in times list

    for time in range(0, len(times)):
        if times[time][0] == start_time:
            start_index = time
        elif times[time][0] == end_time:
            end_index = time
    times = times[start_index:end_index]

    # Loops through all 7 days in the upcoming week, and queries activities
    """for row in Activity.query.all():
        if(row.facility.name == "Fitness Room"):
            print("aight")"""
    for i in range(0, 7):
        # Creates next week list, and sets current date on each loop
        next_week.append(selected_day + timedelta(days=i))
        current_date = selected_day + timedelta(days=i)
        # Iterated through selected hours in the day
        for j in range(0, int(((end_time - start_time) / 100))):
            # Queries activities based on current day, hour, and selected facility
            """if facilities == []:
                activities_in_hour = Activity.query.filter(
                    and_(
                        extract("hour", Activity.start_time)
                        == int((start_time / 100) + j)
                    ),
                    (extract("month", Activity.start_time) == current_date.month),
                    (extract("day", Activity.start_time) == current_date.day),
                ).all()
            else:"""

            activities_in_hour = Activity.query.filter(
                and_(
                    (extract("hour", Activity.start_time) == int(start_time / 100) + j),
                    (extract("month", Activity.start_time) == current_date.month),
                    (extract("day", Activity.start_time) == current_date.day),
                    Activity.facility_id.in_(facilities),
                )
            ).all()
            # Appends the activities queried to the activities list
            activities[i].append(activities_in_hour)

    facilities = Facility.query.all()

    # Renders the HTML page, using parameters for options, the upcoming week, times, and activities
    return render_template(
        "timetable.html",
        form=options,
        week=next_week,
        activities=activities,
        times=times,
        facilities=facilities,
    )


@main_bp.route("/timetable/<start_time>")

# Function used in the rendering of a dynamic select field for times


def endTime(start_time):

    time_array = [
        (900, "9:00"),
        (1000, "10:00"),
        (1100, "11:00"),
        (1200, "12:00"),
        (1300, "13:00"),
        (1400, "14:00"),
        (1500, "15:00"),
        (1600, "16:00"),
        (1700, "17:00"),
    ]

    return jsonify({"Times": time_array})


@main_bp.route("/activities/<activity_id>", methods=["GET", "POST"])
def activity(activity_id):
    activity = Activity.query.filter_by(id=activity_id).first()
    facility_name = activity.facility.name
    # facility_name = Facility.query.filter_by(id=activity.facility_id).first().name

    capacity = {}
    capacity["initial"] = (
        Facility.query.filter_by(id=activity.facility_id).first().capacity
    )
    capacity["booked"] = Booking.query.filter_by(activity_id=activity.id).count()
    capacity["remaining"] = capacity["initial"] - capacity["booked"]
    capacity["percentage_remaining"] = (
        capacity["remaining"] / capacity["initial"]
    ) * 100

    booking = None
    if current_user.is_authenticated:
        booking = Booking.query.filter_by(
            activity_id=activity.id, user_id=current_user.id
        ).first()

    price, price_text, peak_time = get_activity_price(activity)

    form = BookingForm()
    if form.validate_on_submit():
        # create a pending payment
        data = {"activity_id": activity_id, "user_id": current_user.get_id()}

        if price == 0:
            # skip payment and go straight to callback and redirect
            booking_callback(data, None)
            return redirect("/pay/thankyou")
        else:
            desc = "Activity Booking: " + activity.name + " at " + facility_name
            pending_payment = create_pending_payment(
                current_user.get_id(), price, desc, data, "booking", "booking"
            )

            # assign pending payment to user session
            session["pending_payment"] = pending_payment.id

            # redirect the user for payment
            return redirect(url_for("pay_bp.pay"))

    cancel_form = CancelForm()
    if cancel_form.validate_on_submit():
        cancel_booking(current_user.id, activity_id)

        # redirect the user back to the activity page
        return redirect(url_for("pay_bp.pay"))

    return render_template(
        "activity.html",

app/app/main/templates/activities_timetable.html
{% extends "master.html" %} 

{% block main %}
    <div class="container">
        <div class="jumbotron">
            <h1 class="display-4">Activities Timetable</h1>
        </div>

        <p>
            <a class="btn btn-primary" data-toggle="collapse" href="#filters" role="button" aria-expanded="false" aria-controls="collapseExample">
                Show/Hide Filters
            </a>
        </p>

        <div class="collapse" id="filters">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title">Filters</h5>

                    <div>
                        <div class="form-row">
                            <div class="col-sm-3">
                                <strong>Show Facilities</strong>
                            </div>
                            <div class="col-sm-9">
                                {% for facility in facilities %}
                                    <div class="form-check ">
                                        <input class="form-check-input facility_check" type="checkbox" value="{{ facility.id }}" id="facility_check_{{ facility.id }}" name="facility_check_{{ facility.id }}"{% if facility.id in filtered_facilities %} checked{% endif %}>
                                        <label class="form-check-label" for="facility_check_{{ facility.id }}">
                                            {{ facility.name }}
                                        </label>
                                        <br>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>

                        <div class="form-row">
                                <div class="col-sm-3">
                                    <strong>Date Range</strong>
                                </div>

                                <div class="col-sm-9">
                                    Please complete me!
                                </div>
    
                            </div>

                        <div class="form-row">
                            <div class="col-sm-3">
                                <strong>Time Range</strong>
                            </div>

                            <div class="col-sm-9">
                                Please complete me!
                            </div>
                        </div>

                        <div class="form-row">
                            <button class="btn btn-primary" id="applyFiltersButton">Apply Filters</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        {% for date in dates %}
            <h2>{{ date.date.strftime("%A %d %B %Y") }}</h2>
            
            <ul class="activitiesList" style="padding: 0; list-style-type: none;">

                {% if date["activities"] == [] %}
                    <p>There are no activities matching your search on this day.</p>
                {% endif %}

                {% for activity in date["activities"] %}
                    <li style="margin-bottom: 10px;">
    
                        <div class="card">
                            <div class="card-body row align-items-center">
                                <div class="col">
                                    <p class="card-text"><strong>{{ activity.start_time.strftime("%d %b %Y at %H:%M") }}</strong> - {{ activity.name }} at {{ activity.facility.name}}</p>
                                </div>
                                <div class="col-sm-auto">
                                    <a class="btn btn-primary" role="button" aria-pressed="true" href="{{ url_for("main_bp.activity", activity_id = activity.id) }}">View Activity</a>
                                </div>
                            </div>
                        </div>
    
                    </li>
                {% endfor %}
    
            </ul>
        {% endfor %}
    </div>
{% endblock %}

{% block scripts %}

    <script>

        $("#applyFiltersButton").click(function () {
            var newURL = location.protocol + '//' + location.host + location.pathname;
            $(function () {
                $('#datetimepicker3').datetimepicker({
                    format: 'LT'
                });
            });
            var facilities = [];
            $(".facility_check").each(function () {
                if (this.checked) {
                    facilities.push($(this).val())
                }
            });

            newURL += "?facilities=";
            newURL += facilities.join(",");
            newURL += "&time="
            newURL += "12"

            window.location.replace(newURL);
        });

    </script>

{% endblock %}

app/app/main/templates/activity.html
{% extends "master.html" %} 

{% from "macros.html" import activity_info %}

{% block main %}
    <div class="container">
        <div class="jumbotron">
            <h1 class="display-4">{{ activity.name }} at {{facility_name}}</h1>
        </div>

        <div class="row">
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <h2 class="card-title">Booking</h2>

                        {% if booking != None %}
                            <p>You're booked onto this session.</p>

                            <hr />

                            <a class="btn btn-primary" role="button" aria-pressed="true" href="{{ url_for("user_bp.booking", booking_id = booking.id) }}">View Booking</a>
                        {% else %}

                            {% if capacity["initial"] <= capacity["booked"] %}
                                <p>This activity is full so you can't book right now. Please try a different activity.</p>
                            {% else %}
                                <p>You are not booked onto this activity.</p>

                                <p>
                                    Booking Price: {{ price_text }} 

                                    {% if current_user.is_member %}
                                        <span class="badge badge-success">Member's Discount</span>
                                    {% else %}
                                        {% if peak_time %}
                                            <span class="badge badge-warning">Peak</span>
                                        {% else %}
                                            <span class="badge badge-secondary">Off-Peak</span>
                                        {% endif %}
                                    {% endif %}
                                    
                                </p>

                                {% if current_user.is_member %}
                                    <p><em>Members can book activities for free!</em></p>
                                {% endif %}

                                <hr />

                                <div id="book_form">
                                    <form class="form" method="post" action="">
                                        {{ form.csrf_token }}

                                        {{ form.submit(class_="btn btn-primary") }}
                                    </form>
                                </div>
                            {% endif %}

                        {% endif %}
                        
                        
                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <h2>Activity Information</h2>

                {{ activity_info(activity) }}
            </div>
        </div>

            
    </div>
{% endblock %}

app/app/main/templates/bookingPage.html
{% extends "master.html" %} 

{% block main %}

    <h1>Booking Page</h1>
    <b>Activity: </b>{{activity.name}} <br>
    <b>Facility: </b>{{facility_name}} <br>
    <b>Date: </b>{{activity.start_time.strftime("%d/%m/%Y")}} <br>
    <b>Time: </b>{{activity.start_time.strftime("%H:%M")}} - {{activity.end_time.strftime("%H:%M")}} <br>
    <b>Capacity: </b>{{initial_capacity - spaces_booked}} / {{initial_capacity}} spaces remaining <br>
    <b>Price: </b>£{{price}} <br>

    {% if peak_time == True %}
        <b>Price Type: </b> Peak <br>
    {% else %}
        <b>Price Type:</b> Off-Peak <br>

    {% endif %}
    <br>
    {% if already_booked == True %}
        <b>Status:</b> You are booked into this session <br>
    {% else %}
        <b>Status:</b> You are not currently booked into this session <br>
    {% endif %}



    <br><br>
    {% if current_hour < activity.start_time %}
        {% if already_booked == True %}
            <a href=/cancelbooking/{{user.id}}/{{activity.id}} ><input type="button", value="Cancel Booking" /></a>
        {% endif %}

        {%  if current_capacity == 0 and already_booked != True %}
            <input type="button", value="Book Activity" onclick="full()" />
        {% endif %}

        {% if current_capacity != 0 and already_booked != True  %}
        <a href=/book/{{user.id}}/{{activity.id}} > <input type="button", value="Book Activity"/> </a>
        {% endif %}
    {% else %}
    <b>Activity has already happened / is already in session, cannot be booked/cancelled</b>
    {% endif %}

    <script>
        function full() {
            alert("Activity is at capacity, booking cannot be made");
        }
    </script>
{% endblock %}

app/app/main/templates/carousel.html
<div class="container">
    <div class="row">
        <div class="col-sm-7 col-md-9 col-lg-9 col-xl-9 mx-auto">
            <div id="carouselControls" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                    {% for img in images %}
                        {% if img == images[0] %}
                        <div class="carousel-item active">
                        {% else %}
                        <div class="carousel-item">
                        {% endif %}
                            <img class="d-block w-100" src="{{url_for('static', filename='CarouselImages/')}}{{img}}" alt="picture of {{img.split('.')[0]}}">
                        </div>
                    {% endfor %}
                </div>
                <a class="carousel-control-prev" href="#carouselControls" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselControls" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    </div>
</div>

app/app/main/templates/facility.html
{% extends "master.html" %}

{% block main %}
    <h1>{{facility_name}}</h1>
    <h2>Activities available: {{activity_list}}</h2>
    <div class="col-sm-7 col-md-9 col-lg-9 col-xl-9 mx-auto">
        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                {% for image in folder %}
                    {% if image == folder[1] %}
                        <div class="carousel-item active">
                    {% else %}
                        <div class="carousel-item">
                    {% endif %}
                        <img class="d-block w-100" src="/static/{{folder_name}}/{{image}}" alt="picture of {{image.split('.')[0]}}">
                    </div>
                {% endfor %}
            </div>
            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
{% endblock %}

{% block footer %}
<div class="accordion" id="references">
    <a href="" class="text-decoration-none" type="button" data-toggle="collapse" data-target="#collapseReferences" aria-expanded="true" aria-controls="collapseOne">
        References
    </a>
    <div id="collapseReferences" class="collapse" aria-labelledby="headingOne" data-parent="#references">
        <div class="card-body">
            <ul>
                <li>
                    <tiny>http://wallpaperswide.com/olympic_swimming_pool-wallpapers.html</tiny>
                </li>
                <li>
                    https://www.lifestylefitness.co.uk/images/uploads/gallery/1920x1080-Hugh-Baird-2.jpg
                </li>
                <li>
                    https://www.dmu.ac.uk/webimages/About-DMU-images/DMU-Leisure-Centre/sports-hall-img.jpg
                </li>
                <li>
                    https://mk0schoolspace4e2ayv.kinstacdn.com/wp-content/uploads/images/Hayford-Park-Specialisms-Campus-Sports-Hall.jpg
                </li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

app/app/main/templates/index.html
{% extends "master.html" %}

{% block main %}
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
          <h1 class="display-4">Welcome to The Edgier</h1>
          <p class="lead">A beautiful modern multi-purpose sports centre, built for you.</p>
        </div>
    </div>

    {% include "carousel.html" %}
{% endblock %}

{% block footer %}
<div class="accordion" id="references">
    <a href="" class="text-decoration-none" type="button" data-toggle="collapse" data-target="#collapseReferences" aria-expanded="true" aria-controls="collapseOne">
        References
    </a>
    <div id="collapseReferences" class="collapse" aria-labelledby="headingOne" data-parent="#references">
        <div class="card-body">
            <ul>
                <li>
                    <tiny>http://wallpaperswide.com/olympic_swimming_pool-wallpapers.html</tiny>
                </li>
                <li>
                    https://www.lifestylefitness.co.uk/images/uploads/gallery/1920x1080-Hugh-Baird-2.jpg
                </li>
                <li>
                    https://www.dmu.ac.uk/webimages/About-DMU-images/DMU-Leisure-Centre/sports-hall-img.jpg
                </li>
                <li>
                    https://mk0schoolspace4e2ayv.kinstacdn.com/wp-content/uploads/images/Hayford-Park-Specialisms-Campus-Sports-Hall.jpg
                </li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

app/app/main/templates/timetable.html
{% extends "master.html" %} 

{% block main %}
    <br>
    <div class="bg-light">
        <!--<a class="btn btn-primary" data-toggle="collapse" href="#filters" role="button">
                Show/Hide Filters | v

                class="col-3 bg-secondary collapse", (goes before id)
        </a>-->

            
        <div class="row h-100">
            <div class="shadow col-2 rounded", id="filters">
                <form action="" method="post" name="timetable">
                        
                    {{ form.hidden_tag() }}
                    <p>Facility:{{wtf.form_field(form.facility, class='form-control-sm')}}</p>
                    
                    <br><br><br><br><br><br><br><br><br>
                    
                    <p>Week Beginning:{{wtf.form_field(form.start_date, class='form-control-sm')}}</p>
                    <p>Time Start:{{wtf.form_field(form.start_time, class='form-control-sm')}}</p>
                    <p>Time End:{{wtf.form_field(form.end_time, class='form-control-sm')}}</p>
                    <p><input type="submit" class="btn btn-primary" value="Show Timetable"></p>
                    <br><br>
                    <font color="white">(Non-hyperlinked sessions aren't available to be booked)</font>
                </form>
                    

                <script>
                    let start_time_select = document.getElementById('start_time');
                    let end_time_select = document.getElementById('end_time');

                    start_time_select.onchange = function(){
                        start_time = start_time_select.value;
                        fetch('/timetable/'+start_time).then(function(response){
                            response.json().then(function(data){
                                let optionHTMl = '';
                                for(let time of data.Times){
                                    if(time[0] > start_time)
                                        optionHTMl += '<option value="'+time[0]+'">' + time[1] + '</option>';
                                }
                                end_time_select.innerHTML = optionHTMl;
                            });
                        });
                    }
                </script>
            </div>
            <div class="col-10 shadow-none">
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                        <tr>
                        <th> </th>
                        {% if week %}
                            {% for date in week %}
                                <th>{{date.strftime('%A %d/%m')}}</th>
                            {% endfor %}
                        {% endif %}
                        </tr>
                        </thead>
                        <tbody>
                        {% if activities %}
                            {% for hour in range(times|length) %}
                                <tr>
                                    <td><strong>{{times[hour][1]}}</strong></td>
                                    {% for day in activities %}
                                        <td>
                                            {% for activity in day[hour] %}
                                            {% if current_user %}
                                                {% if current_user.is_authenticated %}
                                                <a class="btn btn-info btn-sm" href=/activities/{{activity.id}} , title={{activity.facility_id}}> {{activity.name}}-{{activity.facility.name}}</a><br><br>
                                                {% else %}
                                                <a class="btn btn-info btn-sm disabled" role="button" aria-disabled="true"> {{activity.name}}-{{activity.facility.name}} </a><br><br>
                                                {% endif %}

                                            {% endif %}
                                            {% else %}
                                                <br>
                                            {% endfor %}
                                        </td>
                                    {% endfor %}
                                </tr>
                            {% endfor %}
                        {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>


{% endblock %}