app/app/admin/views.py
from flask import Blueprint, render_template, jsonify, redirect, request
from flask import current_app as app
from app.models import User, Activity, Facility, ActivityType
from datetime import date, timedelta, datetime
from app.admin.forms import SelectActivityType, SubmitDataView
from sqlalchemy.orm import joinedload, contains_eager, subqueryload
from app import db

import time

# Blueprint Configuration
admin_bp = Blueprint(
    "admin_bp",
    __name__,
    template_folder="templates",
    static_folder="static",
    url_prefix="/admin",
)


@admin_bp.route("/", methods=['GET', 'POST'])
def index():
    return render_template("adminHome.html")




@admin_bp.route("/view_timetable", methods=['GET', 'POST'])
def load_timetable_page():
    return render_template("manageTimetable.html")          


@admin_bp.route("/facility/<string:facility>", methods=['GET', 'POST'], defaults={'week_inc':0})
@admin_bp.route("/facility/<string:facility>/<int:week_inc>", methods=['GET', 'POST'])
def get_timetable(facility, week_inc):
    print(facility)
    
    delta = timedelta(days=1)
    w_delta = timedelta(weeks=1)
    dayDate = date.today() + (week_inc*w_delta)
    # get the upcoing week in day from the db
    activities = Activity.query.filter(Activity.start_time >= dayDate, Activity.start_time <= 
            (dayDate + 6 * delta)).all()

    def gen_empty_activty(today, delta):
        return Activity(start_time=(today+delta))

    #generate timetable
    timetable = [[gen_empty_activty(dayDate, (y*delta)) for i in range(9)] for y in range(7)]
    
    
    for activity in activities:
        if activity.facility.name == facility:
            timetable[(activity.start_time.date() - dayDate).days][activity.start_time.hour - 9] = activity


    return jsonify(
                    {
                        "status": "OK",
                        "data":render_template("adminTimetable.html",
                                                timetable=timetable,
                                                facility=facility,
                                                week_inc=week_inc)
                    }
                )




@admin_bp.route("/facility/<string:facility>/<int:week>/<int:day>/<int:hour>", methods=['GET', 'POST'])
def assign_slot(facility, week, day, hour):
    print(facility, day, hour)
    activity_form = SelectActivityType(facility)

    if request.method == "POST":
        
        print(activity_form.activity.data)
        if activity_form.validate_on_submit():
            facility_obj = Facility.query.filter_by(name=facility).first()

            day_date = date.today() + timedelta(days=day-1) + (week*timedelta(weeks=1))
            start_time = datetime(
                year=day_date.year, 
                month=day_date.month,
                day=day_date.day,
                hour=8+hour
            )

            activity = Activity(name=activity_form.activity.data,
                                start_time=start_time,
                                end_time=start_time+timedelta(hours=1),
                                facility_id=facility_obj.id)

            print(activity)

            db.session.add(activity)
            db.session.commit()

            return get_timetable(facility, week)


        else:
            return jsonify(
                {
                    "status": "BAD",
                    "data":render_template("bookActivity.html", 
                                            activity_form=activity_form,
                                            facility=facility,
                                            week=week,
                                            day=day,
                                            hour=hour)
                }
            )
 
    return jsonify(
                    {
                        "status": "OK",
                        "data":render_template("bookActivity.html",
                                                activity_form=activity_form,
                                                facility=facility,
                                                week=week,
                                                day=day,
                                                hour=hour)
                    }
                )




@admin_bp.route("/facility/<int:activity_id>", methods=['GET', 'POST'])
def manage_slot(activity_id):

    activity = Activity.query.get(activity_id)


    return jsonify(
                    {
                        "status": "OK",
                        "data":render_template("viewActivity.html",
                                                activity=activity)
                    }
                )






@admin_bp.route("/view_statistics", methods=['GET', 'POST'])
def load_statistics_page():
    return render_template("statistics.html")



## --------------------------------- GET CHART DATA ------------------------------------ ##


@admin_bp.route("/stats",methods=['GET', 'POST'], defaults={'facility':None, 'activity':None})
@admin_bp.route("/stats/<string:facility>",methods=['GET', 'POST'], defaults={'activity':None})
@admin_bp.route("/stats/<string:facility>/<string:activity>",methods=['GET', 'POST'])
def get_stats(facility, activity):

    months =3
    dayDate = date.today()
    delta = timedelta(days=1)
    w_delta = timedelta(weeks=1)

    start = time.time()

    offset = 6 - dayDate.weekday()
    start_date = dayDate + (offset*delta)
    
    i = 0
    labels = []
    while i < months*4:
        labels.insert(0,start_date - (i*w_delta))
        i += 1 

    
    if facility == None:
        activities = (
            Activity.query
                .options(subqueryload(Activity.users))
                .filter(Activity.start_time > (labels[len(labels)-1] - timedelta(weeks=4*months)),
                        Activity.start_time <= labels[len(labels)-1])
                .all()
        )
    elif activity == None:
        activities = (
                    Activity.query
                        .join(Activity.users)
                        .options(contains_eager('users'))
                        .join(Activity.facility) 
                        .filter(Activity.start_time > (labels[len(labels)-1] - timedelta(weeks=4*months)),
                                Activity.start_time <= labels[len(labels)-1])
                        .filter(Facility.name == facility)
                        .all()
                )
    else:
        activities = (
                    Activity.query
                        .join(Activity.facility)
                        .filter(Activity.name == Activity)
                        .filter(Activity.start_time > (labels[len(labels)-1] - timedelta(weeks=4*months)),
                                Activity.start_time <= labels[len(labels)-1])
                        .filter(Facility.name == facility)
                        .all()
                )
    
    
    if facility == None:
        weekly_data, activities = generate_chart_data(labels, activities, False)
    else:
        weekly_data, activities = generate_chart_data(labels, activities, True)

    print ("START")

    view_form = SubmitDataView(facility)
    view_form.end_date.data = labels[len(labels)-1]
    view_form.start_date.data = labels[len(labels)-2] + delta
    next_url = 2 if len(activities)>20 else None

    print ("ENDING ")
    print(len(activities))
    return jsonify(
                    {
                        "status": "OK",
                        "labels":[x.strftime("%b %d %Y") for x in labels],
                        "data":weekly_data,
                        "activities": render_template("activityList.html",
                            view_form=view_form,
                            activities=activities[:20],
                            facility=facility,
                            next_url=next_url,
                            prev_url=1)
                    }
                )




def generate_chart_data(labels, activities, is_act_type):

    activities = sorted(
        activities,
        key=lambda x: x.start_time
    )

    week_count = 0
    label_index = 0

    user_counts = {"overall":[]}
    activity_list = []
    
    for i, activity in enumerate(activities):

        if activity.start_time.date() >= labels[label_index]:
            user_counts['overall'].append(week_count)
            week_count = 0
            label_index += 1

        week_count += len(activity.users)

        if is_act_type:
            if not activity.name in user_counts:
                user_counts[activity.name] = [0 for i in range(len(labels))]
            user_counts[activity.name][label_index] += len(activity.users)
        else:
            if not activity.facility_id in user_counts:
                user_counts[activity.facility_id] = [0 for i in range(len(labels))]
            user_counts[activity.facility_id][label_index] += len(activity.users)

        if label_index == len(labels)-2:
            activity_list.append(activity)

        if i == len(activities)-1:
            user_counts['overall'].append(week_count)
            break

    if not is_act_type:
        user_counts = get_facilty_name(user_counts)
    
    return user_counts, list(reversed(activity_list))




def get_facilty_name(dict):
    new_dict = {}

    for fac_id in dict:
        if isinstance(fac_id, int):
            facility = Facility.query.get(fac_id)
            new_dict[facility.name] = dict[fac_id]
        else:
            new_dict[fac_id] = dict[fac_id]

    return new_dict



# ------------------------------------------------ per activity data view -------------------------------

@admin_bp.route("/stats/activity_history/",
                methods=['POST'],
                defaults={'facility':None,'page':1})
@admin_bp.route("/stats/activity_history/<string:facility>",
                methods=['POST'],
                defaults={'page':1})
@admin_bp.route("/stats/activity_history/<string:facility>/<int:page>",

app/app/admin/templates/activityList.html
{% block activityList %}
    <div class="spaceUp">
        <form action="{{ url_for('admin_bp.activity_history', facility=facility) }}"
        id="view_data_form" class="formContainer"  method="post" role="form">
            {{ view_form.hidden_tag() }}
            <div class="row justify-content-between">
                <div class="col-auto mr-auto">
                    <div class="row">
                        <div class="form-group spaceLeft">
                            {% if facility %}
                                {{ view_form.activity.label }}<br>
                                {{ view_form.activity(**{ "class":"form-control"}) }}
                                <div class="form-control-feedback">
                                    {% for error in view_form.activity.errors %}
                                        {{ error }}
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>

                        <div class="form-group spaceLeft">
                            {{ view_form.start_date.label }}<br>
                            {{ view_form.start_date(**{ "class":"form-control"}) }}
                            <div class="form-control-feedback">
                                {% for error in view_form.start_date.errors %}
                                    {{ error }}
                                {% endfor %}
                            </div>
                        </div>

                        <div class="form-group spaceLeft">
                            {{ view_form.end_date.label }}<br>
                            {{ view_form.end_date(**{ "class":"form-control"}) }}
                            <div class="form-control-feedback ">
                                {% for error in view_form.end_date.errors %}
                                    {{ error }}
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-auto align-self-center">
                    <button type="submit" class="btn btn-primary">search</button>
                </div>
            </div>
        </form>
    </div>
    <div class="row d-flex justify-content-between spaceUp activity_detail">
        <div class="col text-center">Date</div>
        <div class="col text-center">Activity</div>
        <div class="col text-center"><p>Members</p><span>total</span></div>
        <div class="col text-center"><p>Non-members</p><span>total</span></div>
        <div class="col text-center"><p>Revenue</p><span>total</span></div>
    </div>
    {% for activity in activities %}
        <div class="row d-flex justify-content-between spaceUp activity_detail">
            <div class="col text-center">{{activity.start_time.strftime("%d/%m/%Y, %H:%M")}}</div>
            <div class="col text-center">{{activity.name}}</div>
            <div hidden>
                {% set  members = [] %}
                {% set  non_members = [] %}
                {% for user in activity.users %}
                    {% if user.user.is_member() %}
                        {{ members.append(user) }}
                    {% else %}
                        {{ non_members.append(user) }}
                    {% endif %}
                {% endfor %}
            </div>
            <div class="col text-center">{{members|length}}</div>
            <div class="col text-center">{{non_members|length}}</div>
            <div class="col text-center">revenue</div>
        </div>
    {% endfor %}
    <div class="row justify-content-between">
        <button class="{% if prev_url %}btn btn-primary change_page{% else %}btn btn-secondary{% endif %}"
            dest="{{ url_for('admin_bp.activity_history',  facility=facility, page=1) }}">prev {{prev_url}}</button>
        <button class="{% if next_url %}btn btn-primary change_page{% else %}btn btn-secondary{% endif %}"
            dest="{{ url_for('admin_bp.activity_history',  facility=facility, page=1) }}">next {{next_url}}</button>
    </div>
{% endblock %}

app/app/admin/templates/admin.html
{% extends "master.html" %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('.static', filename='admin.css') }}" />
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.bundle.js"></script>
{% endblock %}


{% block main %}
    {% include "adminToolbar.html" %}
    {% block adminCont %}
    {% endblock %}
{% endblock %}


{% block scripts %}
    <script type="text/javascript" src="{{ url_for('.static', filename='admin.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('.static', filename='chart.js') }}"></script>
{% endblock %}

app/app/admin/templates/adminHome.html
{% extends "admin.html" %} 

{% block adminCont %}
    <div id="admin_content" class="container">
        <div class="jumbotron">
            <h1 class="display-4">Admin home portal</h1>
        </div>
    </div>
{% endblock %}

app/app/admin/templates/adminTimetable.html
{% block timetable %}
<div class="row justify-content-between">
    <button dest="{{url_for('admin_bp.get_timetable',facility=facility, week_inc=week_inc-1)}}" class="getAdminTimetable btn btn-primary">prev</button>
    <button dest="{{url_for('admin_bp.get_timetable',facility=facility, week_inc=week_inc+1)}}" class="getAdminTimetable btn btn-primary">next</button>
</div>
<div class="row">
    <div class="table-responsive">
        <table class="table table-striped table-dark">
            <thead>
            <tr>
            <th> </th>
                {% for day in timetable %}
                    <div>
                        <th>{{day[0].start_time.strftime('%d/%m/%Y')}}</th>
                    </div>
                {% endfor %}
                </tr>
            </thead>
            <tbody>
            {% for hour in range(9) %}
                <tr>
                    <td><strong>{{hour+9}}:00</strong></td>
                    {% for day in timetable %}
                        {% if day[hour].name %}
                            <td class="view_activity" dest="{{url_for('admin_bp.manage_slot', activity_id=day[hour].id)}}" data-toggle="modal" data-target="#dynamicModal"> {{day[hour].name}}</p>
                        {% else %}
                            <td class="available_activity" dest="{{url_for('admin_bp.assign_slot', facility=facility, week=week_inc, hour=hour+1, day=loop.index)}}" data-toggle="modal" data-target="#dynamicModal" >available</p>
                        {% endif %}
                    {% endfor %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{%  endblock %}

app/app/admin/templates/adminToolbar.html
{% block toolbar %}

<div class="container toolbar">
    <div class="row">
        <a href="{{url_for('admin_bp.load_timetable_page')}}" class="btn btn-primary spaceLeft">manage timetable</a>
        <button class="btn btn-primary spaceLeft change_admin_view">manage facilities</button>
        <button class="btn btn-primary spaceLeft change_admin_view">manage users</button>
        <a href="{{url_for('admin_bp.load_statistics_page')}}" class="btn btn-primary spaceLeft">view statistics</a>
    </div>
</div>

{% endblock %}

app/app/admin/templates/bookActivity.html
{% block bookActivityPopup %}

<div class="modal-content">
    <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Book Activity</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <form action="{{ url_for('admin_bp.assign_slot', week=week, facility=facility, day=day,hour=hour)}}" class="book_activity_slot" method="post" role="form">
            {{ activity_form.hidden_tag() }}
            <div class="form-group">
                {{ activity_form.activity.label }}<br>
                {{ activity_form.activity(**{ "class":"form-control"}) }}
                <div class="form-control-feedback">
                    {% for error in activity_form.activity.errors %}
                        {{ error }}
                    {% endfor %}
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
</div>
{% endblock %}

app/app/admin/templates/manageTimetable.html
{% extends "admin.html" %} 

{% block adminCont %}
<div class="container spaceUp">
    <div class="dynamic_content">   

        <div class="facility_list row">
            <button dest="{{url_for('admin_bp.get_timetable',facility='Swimming Pool')}}" type="submit" class="getAdminTimetable btn btn-outline-primary">
                Swimming Pool
            </button>
            <button dest="{{url_for('admin_bp.get_timetable',facility='Fitness Room')}}" type="button" class="getAdminTimetable btn btn-outline-primary spaceLeft">
                Fitness room
            </button>
            <button dest="{{url_for('admin_bp.get_timetable',facility='Squash Court 1')}}" type="submit" class="getAdminTimetable btn btn-outline-primary spaceLeft">
                Squash courts
            </button>
            <button dest="{{url_for('admin_bp.get_timetable',facility='Swimming Pool')}}" type="submit" class="getAdminTimetable btn btn-outline-primary spaceLeft">
                Sports hall
            </button>
        </div>
    </div>
</div>
<div id="timetableContainer" class="container"></div>
{% endblock %}

app/app/admin/templates/statistics.html
{% extends "admin.html" %} 

{% block adminCont %}
    <div class="container">
        <div class="facility_list row space up">
            <button dest="{{url_for('admin_bp.get_stats')}}" class="download_chart_data btn btn-outline-primary spaceLeft">
                Sports center
            </button>
            <button dest="{{url_for('admin_bp.get_stats',facility='Swimming Pool')}}" class="download_chart_data btn btn-outline-primary spaceLeft">
                Swimming Pool
            </button>
            <button dest="{{url_for('admin_bp.get_stats',facility='Fitness Room')}}" class="download_chart_data btn btn-outline-primary spaceLeft">
                Fitness room
            </button>
            <button dest="{{url_for('admin_bp.get_stats',facility='Squash Court 1')}}" class="download_chart_data btn btn-outline-primary spaceLeft">
                Squash courts
            </button>
            <button dest="{{url_for('admin_bp.get_stats',facility='Swimming Pool')}}"  class="download_chart_data btn btn-outline-primary spaceLeft">
                Sports hall
            </button>
        </div>
    </div>


    <meta name="stat_data_url" dest='{{url_for("admin_bp.get_stats")}}'/>
    <div class="container">
        <canvas id="myChart" width="600" height="400"></canvas>
    </div>

    <div class="text-center" id="loading_spinner">
        <div class="spinner-border" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>

    <div class="container" id="week_selection_toolbar">

    </div>

    <div class="container" id="activity_listy_container">

    </div>

{% endblock %}

app/app/admin/templates/viewActivity.html
{% block bookActivityPopup %}

    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">{{activity.name}}</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <div>
                <h3>Attendee's</h3>
                
                {% for user in activity.users %}
                    <div class="row justify-content-between border">
                        <div class="col-auto mr-auto">
                            <p>{{user.user.first_name}}</p>
                        </div>
                        <div class="col-auto">
                            <button class="btn btn-outline-danger">remove</button>
                        </div>
                    </div>
                    
                {% endfor %}

            </div>
            <button class="btn btn-primary" >Add member</button>
        </div>
    </div>

{% endblock %}