app/app/main/views.py
from flask import (
    Blueprint,
    render_template,
    redirect,
    url_for,
    jsonify,
    session,
    request,
)
from flask import current_app as app
from flask import abort
from flask_login import current_user, login_user, logout_user, login_required
from app.main.forms import Signup, TimetableOptions, BookingForm, CancelForm
from app import db, bcrypt
from app.models import User, Activity, Facility, Booking
from datetime import datetime, timedelta, date, time
from sqlalchemy import extract, and_
from app.user.views import booking_email_confirmation
import os
import html
import decimal
import re
from app.pay.payments import create_pending_payment
from app.main.callbacks import create_booking as booking_callback
from app.pay.payments import redirections as pay_redirects
from .helpers import get_activity_price


# Blueprint Configuration
main_bp = Blueprint(
    "main_bp", __name__, template_folder="templates", static_folder="static"
)


@main_bp.route("/index", methods=["GET"])
@main_bp.route("/", methods=["GET"])
def index():
    """Homepage route."""
    images = os.listdir(os.path.join(app.static_folder, "CarouselImages"))
    return render_template("index.html", images=images)


@main_bp.route("/facility/<facility_choice>")
def facility(facility_choice):
    facility_name_list = re.findall("[A-Z][^A-Z]*", facility_choice)
    facility_name = ""
    for i in facility_name_list:
        facility_name = facility_name + i + " "
    facility_name = facility_name.strip()
    if facility_name == "Squash Courts":
        facility_name = "Squash Court 1"
    if db.session.query(Facility.name).filter_by(name=facility_name).scalar() is None:
        return abort(404)
    imageFolder = facility_choice + "Images"
    folder = os.listdir(os.path.join(app.static_folder, imageFolder))

    facility_id = Facility.query.filter_by(name=facility_name).first().id
    activities = (
        Activity.query.filter_by(facility_id=facility_id).group_by(Activity.name).all()
    )
    for i in range(0, len(activities)):
        activities[i] = activities[i].name

    activity_list = ",".join(activities)

    return render_template(
        "facility.html",
        folder=folder,
        folder_name=imageFolder,
        facility_name=facility_name,
        activity_list=activity_list,
    )


@main_bp.route("/signup", methods=["GET", "POST"])
def signup():
    signup_form = Signup()
    if signup_form.validate_on_submit():
        create_user(
            signup_form.first_name.data,
            signup_form.last_name.data,
            signup_form.email.data,
            signup_form.password.data,
            signup_form.emergency_number.data,
            signup_form.dob.data,
        )
        return redirect(url_for("main_bp.index"))
    return render_template("signup.html", form=signup_form)


def create_user(first_name, last_name, email, password, emergency_num, dob):
    # create new user, hash password and add to the database
    password_hash = bcrypt.generate_password_hash(password).decode("utf-8")
    new_user = User(
        first_name=first_name,
        last_name=last_name,
        email=email,
        password=password_hash,
        emergency_number=emergency_num,
        dob=dob,
        user_type=3,
    )
    db.session.add(new_user)
    db.session.commit()


# Main code ran when on timetable page


@main_bp.route("/timetable", methods=["GET", "POST"])
def timetable():

    # Sets current day and creates list of days in upcoming month

    today = datetime.now()
    upcoming_month = []
    times = [
        (900, "9:00"),
        (1000, "10:00"),
        (1100, "11:00"),
        (1200, "12:00"),
        (1300, "13:00"),
        (1400, "14:00"),
        (1500, "15:00"),
        (1600, "16:00"),
        (1700, "17:00"),
    ]

    for i in range(0, 28):
        upcoming_month.append(today + timedelta(days=i))

    # Creates instance of the timetable options form
    # Sets the range of choices for start time, end time, and start date

    options = TimetableOptions()

    options.start_time.choices = times[0:8]
    options.end_time.choices = times[1:9]

    options.start_date.choices = [
        (day.strftime("%x"), day.strftime("%d/%m/%Y")) for day in upcoming_month
    ]

    # After submitting the timetable options, generate timetable function is run

    if options.validate_on_submit():
        return generateTimetable(options)

    # Loads the html page, using the options form created

    facilities = Facility.query.all()

    return render_template("timetable.html", form=options, facilities=facilities)


def generateTimetable(options):

    # Reads completed form data
    start_time = options.start_time.data
    end_time = options.end_time.data
    selected_day = datetime.strptime(options.start_date.data, "%x")
    activities = [[], [], [], [], [], [], []]
    next_week = []

    facilities = options.facility.data

    if len(facilities) > 0:
        for i in range(0, len(facilities)):
            facilities[i] = Facility.query.filter_by(name=facilities[i]).first().id

    times = [
        (900, "9:00"),
        (1000, "10:00"),
        (1100, "11:00"),
        (1200, "12:00"),
        (1300, "13:00"),
        (1400, "14:00"),
        (1500, "15:00"),
        (1600, "16:00"),
        (1700, "17:00"),
    ]

    # Finds index position of start and end time in times list

    for time in range(0, len(times)):
        if times[time][0] == start_time:
            start_index = time
        elif times[time][0] == end_time:
            end_index = time
    times = times[start_index:end_index]

    # Loops through all 7 days in the upcoming week, and queries activities
    """for row in Activity.query.all():
        if(row.facility.name == "Fitness Room"):
            print("aight")"""
    for i in range(0, 7):
        # Creates next week list, and sets current date on each loop
        next_week.append(selected_day + timedelta(days=i))
        current_date = selected_day + timedelta(days=i)
        # Iterated through selected hours in the day
        for j in range(0, int(((end_time - start_time) / 100))):
            # Queries activities based on current day, hour, and selected facility
            """if facilities == []:
                activities_in_hour = Activity.query.filter(
                    and_(
                        extract("hour", Activity.start_time)
                        == int((start_time / 100) + j)
                    ),
                    (extract("month", Activity.start_time) == current_date.month),
                    (extract("day", Activity.start_time) == current_date.day),
                ).all()
            else:"""

            activities_in_hour = Activity.query.filter(
                and_(
                    (extract("hour", Activity.start_time) == int(start_time / 100) + j),
                    (extract("month", Activity.start_time) == current_date.month),
                    (extract("day", Activity.start_time) == current_date.day),
                    Activity.facility_id.in_(facilities),
                )
            ).all()
            # Appends the activities queried to the activities list
            activities[i].append(activities_in_hour)

    facilities = Facility.query.all()

    # Renders the HTML page, using parameters for options, the upcoming week, times, and activities
    return render_template(
        "timetable.html",
        form=options,
        week=next_week,
        activities=activities,
        times=times,
        facilities=facilities,
    )


@main_bp.route("/timetable/<start_time>")

# Function used in the rendering of a dynamic select field for times


def endTime(start_time):

    time_array = [
        (900, "9:00"),
        (1000, "10:00"),
        (1100, "11:00"),
        (1200, "12:00"),
        (1300, "13:00"),
        (1400, "14:00"),
        (1500, "15:00"),
        (1600, "16:00"),
        (1700, "17:00"),
    ]

    return jsonify({"Times": time_array})


@main_bp.route("/activities/<activity_id>", methods=["GET", "POST"])
def activity(activity_id):
    activity = Activity.query.filter_by(id=activity_id).first()
    facility_name = activity.facility.name
    # facility_name = Facility.query.filter_by(id=activity.facility_id).first().name

    capacity = {}
    capacity["initial"] = (
        Facility.query.filter_by(id=activity.facility_id).first().capacity
    )
    capacity["booked"] = Booking.query.filter_by(activity_id=activity.id).count()
    capacity["remaining"] = capacity["initial"] - capacity["booked"]
    capacity["percentage_remaining"] = (
        capacity["remaining"] / capacity["initial"]
    ) * 100

    booking = None
    if current_user.is_authenticated:
        booking = Booking.query.filter_by(
            activity_id=activity.id, user_id=current_user.id
        ).first()

    price, price_text, peak_time = get_activity_price(activity)

    form = BookingForm()
    if form.validate_on_submit():
        # create a pending payment
        data = {"activity_id": activity_id, "user_id": current_user.get_id()}

        if price == 0:
            # skip payment and go straight to callback and redirect
            booking_callback(data, None)
            return redirect("/pay/thankyou")
        else:
            desc = "Activity Booking: " + activity.name + " at " + facility_name
            pending_payment = create_pending_payment(
                current_user.get_id(), price, desc, data, "booking", "booking"
            )

            # assign pending payment to user session
            session["pending_payment"] = pending_payment.id

            # redirect the user for payment
            return redirect(url_for("pay_bp.pay"))

    cancel_form = CancelForm()
    if cancel_form.validate_on_submit():
        cancel_booking(current_user.id, activity_id)

        # redirect the user back to the activity page
        return redirect(url_for("pay_bp.pay"))

    return render_template(
        "activity.html",

app/app/templates/flash.html
{% block flash %}
    <div class="container">
        <div class="alert alert-{{ category }} alert-dismissible">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <h3>{{message}}</h3>
        </div>
    </div>
{% endblock %}

app/app/templates/macros.html
{% macro activity_info(activity) %}

    <dl class="row">

        <dt class="col-sm-3">Activity</dt>
        <dd class="col-sm-9">{{ activity.name }}</dd>

        <dt class="col-sm-3">Facility</dt>
        <dd class="col-sm-9">{{ activity.facility.name }}</dd>

        <dt class="col-sm-3">Date</dt>
        <dd class="col-sm-9">{{ activity.start_time.strftime("%d/%m/%Y") }}</dd>

        <dt class="col-sm-3">Time</dt>
        <dd class="col-sm-9">
            {{ activity.start_time.strftime("%H:%M")}} - {{ activity.end_time.strftime("%H:%M") }}
            {% if activity.is_peak_time() %}
                <span class="badge badge-warning">Peak</span>
            {% else %}
                <span class="badge badge-secondary">Off-Peak</span>
            {% endif %}
        </dd>

        <dt class="col-sm-3">Spaces Remaining</dt>
        <dd class="col-sm-9">
            <div class="row">
                <div class="col-sm-auto">{{ activity.remaining_capacity() }} / {{ activity.initial_capacity() }}</div>
                <div class="col">
                    <div class="progress" style="height: 20px">
                        {% if activity.capacity_ratio() * 100 > 40 %}
                            <div class="progress-bar progress-bar-striped bg-success" role="progressbar" style="width: {{ activity.capacity_ratio() * 100 }}%;" aria-valuenow="{{ activity.capacity_ratio() * 100 }}" aria-valuemin="0" aria-valuemax="100"></div>
                        {% elif activity.capacity_ratio() * 100 > 20 %}
                            <div class="progress-bar progress-bar-striped bg-warning" role="progressbar" style="width: {{ activity.capacity_ratio() * 100 }}%;" aria-valuenow="{{ activity.capacity_ratio() * 100 }}" aria-valuemin="0" aria-valuemax="100"></div>
                        {% else %}
                            <div class="progress-bar progress-bar-striped progress-bar-animated bg-danger" role="progressbar" style="width: {{ activity.capacity_ratio() * 100 }}%;" aria-valuenow="{{ activity.capacity_ratio() * 100 }}" aria-valuemin="0" aria-valuemax="100"></div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </dd>

    </dl>

{% endmacro %}

{% macro payment_details(payment) %}

    <dl class="row">

        <dt class="col-sm-3">Description</dt>
        <dd class="col-sm-9">{{ payment.description }}</dd>

        <dt class="col-sm-3">Amount</dt>
        <dd class="col-sm-9">£{{ "%.2f" % payment.get_price_decimal() }}</dd>

        <dt class="col-sm-3">Time</dt>
        <dd class="col-sm-9">{{ payment.time.strftime("%d %b %Y at %H:%M") }}</dd>

        <dt class="col-sm-3">Card Used</dt>
        <dd class="col-sm-9">{{ payment.card.get_anon_number() }}</dd>

    </dl>

{% endmacro %}

{% macro booking_qrcode(booking) %}
    {% set qrstring = [config['QR_KEY'],booking.id]|join(",") %}
    <img id="qrcode" class="img-fluid" src="{{ qrstring | qrcode }}">
{% endmacro %}

app/app/templates/master.html
{% import "bootstrap/wtf.html" as wtf %}

<!doctype html>
<html lang="en">
        <head>
            <!-- Required meta tags -->
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

            <!-- Bootstrap CSS -->
            {% block css %}{% endblock %}
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
            <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}" />
            <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='ribbon.css') }}" />
            <title>{{title}}</title>

            {% if meta %}
                <meta value='{{meta}}'/>
            {% endif %}
        </head>
    <body>
        {% include 'nav.html' %}
        <div class="content" id="main">
            {% with messages = get_flashed_messages(with_categories=true) %} 
                {% if messages %} 
                    {% for category, message in messages %}
                        <div class="container">
                            <div class="alert alert-{{ category }} alert-dismissible">
                                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                                {{message}}
                            </div>
                        </div>
                    {% endfor %} 
                {% endif %} 
            {% endwith %} 
      
            {% block main %}{% endblock %} 
        </div> 

        <footer class="footer bg-dark spaceUp">
            <div class="container text-center">
                {% block footer %}{% endblock %}
            </div>
        </footer>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/jquery-form-validation/dist/jquery.form-validation.min.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js" ></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        {% block scripts %}{% endblock %}
        <script type="text/javascript" src="{{ url_for('static', filename='main.js') }}"></script>
    </body>
</html>

app/app/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light" id="navbar">
        <a class="navbar-brand" href="{{url_for('main_bp.index')}}">THE EDGIER</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('main_bp.index')}}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('main_bp.timetable')}}">Timetable</a>
            </li>
            <li class="nav-item dropdown">
                <div class="dropdown">
                    <a class="nav-link dropdown-toggle" role="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Facilities
                    </a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                      <a class="dropdown-item" href="/facility/SwimmingPool">Swimming Pool</a>
                      <a class="dropdown-item" href="/facility/FitnessRoom">Fitness Room</a>
                      <a class="dropdown-item" href="/facility/SquashCourts">Squash Courts</a>
                      <a class="dropdown-item" href="/facility/SportsHall">Sports Hall</a>
                    </div>
                  </div>
            </li>
            {% if current_user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        My Account
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{{ url_for('user_bp.bookings') }}">My Bookings</a>
                        <a class="dropdown-item" href="{{ url_for('user_bp.userAccount') }}">Account</a>
                        {% if current_user.is_member() %}
                            <a class="dropdown-item" href="{{url_for('membership_bp.membership_manage')}}">Manage Membership</a>
                        {% else %}
                            <a class="dropdown-item" href="{{url_for('membership_bp.membership_join')}}">Become a Member</a>
                        {% endif %}
                        <a class="dropdown-item" href="{{ url_for('user_bp.payments') }}">My Payments</a>
                        {% if current_user.is_employee() %}
                            <a class="dropdown-item" href="{{url_for('admin_bp.index')}}">Admin portal</a>
                        {% endif %}
                    </div>
                </li>

                {% if current_user.has_pending_payment() %}
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('pay_bp.pay')}}">Pay</a>
                </li>
                {% endif %}
            {% endif %}
            <div class="authCont">
                {% if current_user.is_anonymous %}
                    <li class="nav-item">
                        <a class="nav-link" href="" data="{{ url_for('user_bp.login') }}" class="btn btn-primary sideNavButton" data-toggle="modal" data-target="#dynamicModal" id="showLoginForm">
                            Login
                        </a>
                    </li>

                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('user_bp.logout') }}">Logout</a>
                        </li>
                    {% endif %}
                  </div> 
                  <!-- modal for dynamic forms -->
                <div class="modal fade" id="dynamicModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" id="dynamicModalInsert" role="document">
                </div>
            </div>
          </ul>
        </div>
</nav>