app/app/user/views.py
from flask import (
    Blueprint,
    render_template,
    jsonify,
    request,
    redirect,
    url_for,
    abort,
    session,
    flash,
)
from flask import current_app as app
from flask_login import current_user, login_user, logout_user, login_required

# need to change these the not camel casing
from app.user.forms import (
    Signup,
    LoginForm,
    EditDetails,
    confirmPasswordForm,
    changePasswordForm,
    CancelBookingForm,
    VerifyForm,
)
from app import db, bcrypt
from app.models import User, Activity, Booking, PaymentLog, IPLog

from flask import current_app as app

from sqlalchemy import extract, and_
from datetime import datetime

from app.email import send_email
from email.mime.text import MIMEText

import random
import json
import re
from urllib.request import urlopen
import hashlib
from app.main.helpers import get_activity_price

try:
    from flask_weasyprint import render_pdf, HTML
except:
    pass

# from app.main.forms import ()

# Blueprint Configuration
user_bp = Blueprint(
    "user_bp",
    __name__,
    template_folder="templates",
    static_folder="static",
    url_prefix="/user",
)


@user_bp.route("/", methods=["GET"])
def home():
    """Homepage route."""
    return render_template("user.html")


# ------------------------------sign up ---------------------------------------


@user_bp.route("/privacyPolicy", methods=["GET"])
def privacy_policy():
    return render_template("privacy_policy.html")


@user_bp.route("/signup", methods=["GET", "POST"])
def signup():
    signup_form = Signup()
    if signup_form.validate_on_submit():
        create_user(
            signup_form.first_name.data,
            signup_form.last_name.data,
            signup_form.email.data,
            signup_form.password.data,
            signup_form.emergency_number.data,
            signup_form.dob.data,
        )

        return redirect(url_for("user_bp.userAccount"))

    for fieldName, errorMessages in signup_form.errors.items():
        for err in errorMessages:
            print(err)

    return render_template("signup.html", form=signup_form)


def create_user(first_name, last_name, email, password, emergency_num, dob):
    # create new user, hash password and add to the database
    password_hash = bcrypt.generate_password_hash(password).decode("utf-8")
    new_user = User(
        first_name=first_name,
        last_name=last_name,
        email=email,
        password=password_hash,
        emergency_number=emergency_num,
        dob=dob,
        user_type=3,
    )
    db.session.add(new_user)
    db.session.commit()
    login_user(new_user)


# --------------------------login --------------------------------------------
@user_bp.route("/validateLogin", methods=["GET", "POST"])
def validate_login():
    verify = VerifyForm()
    if verify.validate_on_submit():
        code_received = datetime.now()
        diff = code_received - session["code_sent"]
        min_diff = diff.seconds // 60
        session.pop("code_sent")
        if (
            hashlib.md5(verify.code.data.encode("utf-8")).hexdigest()
            == session["verify_code"]
            and min_diff <= 5
        ):
            user = User.query.get(session["login_user"])
            new_log = IPLog(
                user_id=user.id,
                ip_addr=hashlib.md5(request.remote_addr.encode("utf-8")).hexdigest(),
            )
            db.session.add(new_log)
            db.session.commit()
            session.pop("login_user")
            session.pop("verify_code")
            login_user(user)
            return redirect(url_for("user_bp.home"))
        else:
            session.pop("login_user")
            session.pop("verify_code")
            # flash error message
            return redirect(url_for("main_bp.index"))

    else:
        uid, name, email = current_user.id, current_user.first_name, current_user.email
        ip_addr = request.remote_addr
        log = IPLog.query.get((uid, hashlib.md5(ip_addr.encode("utf-8")).hexdigest()))
        if log != None:
            return redirect(url_for("user_bp.home"))
        else:
            logout_user()
            code = random.randint(100000, 999999)
            print(code)
            session["verify_code"] = hashlib.md5(str(code).encode("utf-8")).hexdigest()
            session["login_user"] = uid
            session["code_sent"] = datetime.now()
            if app.debug:
                print("Code: {}".format(code))

            response = urlopen("http://ipinfo.io/json")
            data = json.load(response)
            city = data["city"]
            country = data["country"]
            send_email(
                "Edgier Attempted Login",
                email,
                MIMEText(
                    render_template("new_login_email.html", code=code, name=name),
                    "html",
                ),
            )
            return render_template(
                "new_login.html",
                verify_form=verify,
                email=email,
                ip_addr=ip_addr,
                city=city,
                country=country,
            )


# login route - returns a form in json response
@user_bp.route("/login", methods=["GET", "POST"])
def login():

    # initialise login form
    login_form = LoginForm()

    # handle login request
    if request.method == "POST":
        if login_form.validate_on_submit():
            # if valid log the user in
            user = User.query.filter_by(email=login_form.email.data).first()
            login_user(user, remember=login_form.remember_me.data)
            # if the user is not a customer redirect them to the administrative home
            if user.user_type != 3:
                return jsonify({"status": "OK", "redirect": url_for("admin_bp.index")})
            else:
                log = IPLog.query.get((user.id, request.remote_addr))
                if log != None:
                    # if valid return json response and flash message
                    return jsonify(
                        {
                            "status": "OK",
                            "flash": render_template(
                                "flash.html",
                                message="You have successfully logged in",
                                category="success",
                            ),
                            "navbar": render_template("nav.html"),
                        }
                    )
                else:
                    return jsonify(
                        {
                            "status": "MEDIUM",
                            "redirect": url_for("user_bp.validate_login"),
                        }
                    )

        # if invalid return a login form with errors as json object
        else:
            return jsonify(
                {
                    "status": "BAD",
                    "data": render_template("loginForm.html", login_form=login_form),
                }
            )
    # if get request return the login form as json object
    else:
        return jsonify(
            {
                "status": "OK",
                "data": render_template("loginForm.html", login_form=login_form),
            }
        )


# ---------------------------------------------- logout -----------------------------

# registers the user as logged out through the flask login manager
@user_bp.route("/logout")
@login_required
def logout():
    logout_user()
    # redirect the user to the home page
    return redirect(url_for("main_bp.index"))


# -------------------------- user account page --------------------------------------------

# get the users account and handle user requests to chanege their details
@user_bp.route("/account", methods=["GET", "POST"])
@login_required
def userAccount():
    # generate edit user details form
    edit_user_form = EditDetails(current_user)
    if edit_user_form.validate_on_submit():
        # if valid then update the userr details
        current_user.first_name = edit_user_form.first_name.data
        current_user.last_name = edit_user_form.last_name.data
        current_user.email = edit_user_form.email.data
        current_user.emergency_number = edit_user_form.emergency_number.data
        current_user.dob = edit_user_form.dob.data
        # save the changes
        db.session.commit()
    # render the users account page this may contain form errors

    # get activities signed up for
    activities = Booking.query.filter_by(user_id=current_user.id).all()
    return render_template(
        "userAccount.html",
        bookings=current_user.bookings,
        edit_user_form=edit_user_form,
        activities=activities,
    )


# ---------------------------- Confirm Password -----------------------------------------

# route to render and handle the user the confirm password form
@user_bp.route("/confirmPassword", methods=["GET", "POST"])
@login_required
def confirmPassword():
    # create an instance of the form
    confirm_password_form = confirmPasswordForm(current_user)

    # if post check for form validation
    if request.method == "POST":
        if confirm_password_form.validate_on_submit():
            # if the password was correct return OK
            return jsonify({"status": "OK"})
        else:
            # if the password was incorrect return the confirm password form with errors as json
            return jsonify(
                {
                    "status": "BAD",
                    "data": render_template(
                        "confirmPasswordForm.html",
                        confirm_password_form=confirm_password_form,
                    ),
                }
            )
    # if a get request return the confirm password form as a json object
    return jsonify(
        {
            "status": "OK",
            "data": render_template(
                "confirmPasswordForm.html", confirm_password_form=confirm_password_form
            ),
        }
    )

app/app/user/templates/booking.html
{% extends "master.html" %}

{% from "macros.html" import activity_info %}

{% block main %}
    <div class="container">
        <div class="jumbotron">
            <h1 class="display-4">Booking #{{ booking.id }}</h1>

            <p class="lead">{{ booking.activity.name }} at {{ booking.activity.facility.name }}</p>
        </div>

        <h2>Activity Information</h2>

        {{ activity_info(booking.activity) }}

        <h2>Booking Information</h2>

        <dl class="row">

            <dt class="col-sm-3">Activity ID</dt>
            <dd class="col-sm-9">{{ booking.activity_id }}</dd>
    
            <dt class="col-sm-3">User ID</dt>
            <dd class="col-sm-9">{{ booking.user_id }}</dd>
    
            <dt class="col-sm-3">Booking Time</dt>
            <dd class="col-sm-9">{{ booking.time_of_booking.strftime("%d %b %Y at %H:%M") }}</dd>

        </dl>

        <h3>Payment Details</h3>

        <dl class="row">

            <dt class="col-sm-3">Payment Card</dt>
            <dd class="col-sm-9">**** **** **** XXXX</dd>

            <dt class="col-sm-3">Payment Amount</dt>
            <dd class="col-sm-9">{{price_text}}</dd>

        </dl>

        <h2>Receipt</h2>

        <ul>
            <li>
                <a href="{{ url_for('user_bp.booking_receipt', booking_id=booking.id) }}" target="_blank">View printable receipt</a>
                (<a href="{{ url_for('user_bp.booking_receipt_pdf', booking_id=booking.id) }}" target="_blank">PDF</a>)
            </li>

            <li>
                <a href="{{ url_for('user_bp.email_receipt', booking_id=booking.id) }}">Email me a receipt</a>
                <!-- Email me a receipt -->
            </li>
        </ul>

        <h2>Manage Booking</h2>

        <div id="cancel_form">
            <form class="form" method="post" action="">
                {{ cancel_form.csrf_token }}

                {{ cancel_form.submit(class_="btn btn-outline-danger") }}
            </form>
        </div>
        
    </div>
{% endblock %}

app/app/user/templates/bookings.html
{% extends "master.html" %}

{% block main %}
    <div class="container">
        <div class="jumbotron">
            <h1 class="display-4">My Bookings</h1>
        </div>

        {% if bookings == [] %}
            <p>You don't have any bookings.</p>

            <p>You can make one by finding an activity you like the look in <a href="{{ url_for("main_bp.timetable") }}">the timetable</a>.</p>
        {% else %}
        <ul id="bookingsList" style="padding: 0; list-style-type: none;">

            {% for booking in bookings %}
                <li style="margin-bottom: 10px;">

                    <div class="card">
                        <div class="card-body row align-items-center">
                            <div class="col">
                                <p class="card-text"><strong>{{ booking.activity.start_time.strftime("%d %b %Y at %H:%M") }}</strong> - {{ booking.activity.name }} at {{ booking.activity.facility.name}}</p>
                            </div>
                            <div class="col-sm-auto">
                                <a class="btn btn-primary" role="button" aria-pressed="true" href="{{ url_for("user_bp.booking", booking_id = booking.id) }}">View Booking</a>
                            </div>
                        </div>
                    </div>

                </li>
            {% endfor %}

        </ul>
        {% endif %}
    </div>
{% endblock %}

app/app/user/templates/confirmPasswordForm.html
{% block confirmPassword %}
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Confirm Password</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <form action='{{url_for("user_bp.confirmPassword")}}' method='POST' id='confirmPasswordForm'>
            {{ confirm_password_form.hidden_tag() }}
            <div class="modal-body">
                <p>Please confirm your password in order to change your details</p>
                <div class="form-group">
                    {% if confirm_password_form.password.errors %}
                        {{ confirm_password_form.password(**{"type":"password", "class":"form-control is-invalid", "data-validator-label":"password", "data-validator":"required"}) }}
                        <div class="form-control-feedback invalid-feedback">
                            {% for error in confirm_password_form.password.errors %}
                                {{ error }}
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ confirm_password_form.password(**{"type":"password", "class":"form-control", "data-validator-label":"password", "data-validator":"required"}) }}
                        <div class="form-control-feedback"></div>
                    {% endif %}
                </div>
                <hr>
                <div class="row justify-content-between spaceUp borderUp">
                    <div class="col col-auto mr-auto">
                        <p>{{ confirm_password_form.submit(class_='btn btn-primary') }}</p>  
                    </div>
                    <div class="col col-auto">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal" >Close</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

app/app/user/templates/edit_user_details.html
{% block edit_user_details %}
    <div class="card userDetails" id="hideEditUserDetails">
        <form action="{{url_for('user_bp.userAccount')}}" method="POST" id='editUserDetailsForm'>
            {{ edit_user_form.hidden_tag() }}
            <div class="card-header ">
                <div class="row justify-content-between">
                    <div >
                        <h3>My Details</h3>
                    </div>
                    <div >
                        <button class="btn btn-primary" type="button" data-toggle="modal" data-target="#dynamicModal" id="getConfirmPassword" data="{{url_for('user_bp.confirmPassword')}}" next='#editUserDetailsForm'>
                            Save
                        </button>
                        <button class="btn btn-secondary switchEditUserDetails" type="button">
                            Cancle
                        </button>
                    </div>
                </div>   
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-3" >
                        <p>Email</p>
                    </div>
                    <div class="col-sm-9">
                        <div class="form-group">
                            {% if edit_user_form.email.errors %}
                                {{ edit_user_form.email(**{"type":"email", "class":"form-control is-invalid", "value":current_user.email,"data-validator-label":"Email", "data-validator":"required|email"}) }}
                                <div class="form-control-feedback invalid-feedback">
                                    {% for error in edit_user_form.email.errors %}
                                        {{ error }}
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ edit_user_form.email(**{"type":"email", "class":"form-control", "value":current_user.email,"data-validator-label":"Email", "data-validator":"required|email"}) }}
                                <div class="form-control-feedback"></div>
                            {% endif %}
                        </div>
                    </div>    
                </div>
                <div class="row">
                    <div class="col-sm-3">
                        <p>First name</p>
                    </div>
                    <div class="col-sm-9">
                        <div class="form-group">
                            {% if edit_user_form.first_name.errors %}
                                {{ edit_user_form.first_name(**{"type":"text", "class":"form-control is-invalid", "value":current_user.first_name,"data-validator-label":"first name", "data-validator":"required"}) }}
                                <div class="form-control-feedback invalid-feedback">
                                    {% for error in edit_user_form.first_name.errors %}
                                        {{ error }}
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ edit_user_form.first_name(**{"type":"text", "class":"form-control", "value":current_user.first_name,"data-validator-label":"first name", "data-validator":"required"}) }}
                                <div class="form-control-feedback"></div>
                            {% endif %}
                        </div>
                    </div>    
                </div>
                <div class="row">
                    <div class="col-sm-3">
                        <p>Last name</p>
                    </div>
                    <div class="col-sm-9">
                        <div class="form-group">
                            {% if edit_user_form.last_name.errors %}
                                {{ edit_user_form.last_name(**{"type":"text", "class":"form-control is-invalid", "value":current_user.last_name, "data-validator-label":"last name","data-validator":"required"}) }}
                                <div class="form-control-feedback invalid-feedback">
                                    {% for error in edit_user_form.last_name.errors %}
                                        {{ error }}
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ edit_user_form.last_name(**{"type":"text", "class":"form-control", "value":current_user.last_name,"data-validator-label":"last name", "data-validator":"required"}) }}
                                <div class="form-control-feedback"></div>
                            {% endif %}
                        </div>
                    </div>    
                </div>
                <div class="row">
                    <div class="col-sm-3">
                        <p>Phone number</p>
                    </div>
                    <div class="col-sm-9">
                        <div class="form-group">
                            {% if edit_user_form.emergency_number.errors %}
                                {{ edit_user_form.emergency_number(**{"type":"tel", "class":"form-control is-invalid", "value":current_user.emergency_number, "data-validator-label":"mobile number", "data-validator":"required|size:11"}) }}
                                <div class="form-control-feedback invalid-feedback">
                                    {% for error in edit_user_form.emergency_number.errors %}
                                        {{ error }}
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ edit_user_form.emergency_number(**{"type":"tel", "class":"form-control", "value":current_user.emergency_number, "data-validator-label":"mobile name", "data-validator":"required|size:11"}) }}
                                <div class="form-control-feedback"></div>
                            {% endif %}
                        </div>
                    </div>    
                </div>
                <div class="row">
                    <div class="col-sm-3">
                        <p>Date of birth</p>
                    </div>
                    <div class="col-sm-9">
                        <div class="form-group">
                            {% if edit_user_form.dob.errors %}
                                {{ edit_user_form.dob(**{"id":"dob", "class":"form-control is-invalid", "value":current_user.dob, "data-validator-label":"date of birth","data-validator":"required"}) }}
                                <div class="form-control-feedback invalid-feedback">
                                    {% for error in edit_user_form.dob.errors %}
                                        {{ error }}
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ edit_user_form.dob(**{"id":"dob","class":"form-control", "data-validator-label":"date of birth", "data-validator":"required"}) }}
                                <div class="form-control-feedback"></div>
                            {% endif %}
                        </div>
                    </div>    
                </div>
            </div>
        </form>
    </div>
{% endblock %}

app/app/user/templates/loginForm.html
{% block login %}
<div class="modal-content">
    <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Login</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <form action="{{ url_for('user_bp.login') }}" id="loginForm" class="formContainer"  method="post" role="form">
            {{ login_form.hidden_tag() }}
            <div class="form-group">
                {{ login_form.email.label }}<br>
                {% if login_form.email.errors %}
                    {{ login_form.email(**{"type":"email", "class":"form-control is-invalid", "id":"inputEmail", "placeholder":"Email","data-validator-label":"Email", "data-validator":"required|email", "data-validator-warnings":"required"}) }}
                    <div class="form-control-feedback invalid-feedback">
                        {% for error in login_form.email.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                {% else %}
                    {{ login_form.email(**{"type":"email", "class":"form-control", "id":"inputEmail", "placeholder":"Email", "data-validator-label":"Email", "data-validator":"required|email"}) }}
                    <div class="form-control-feedback"></div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ login_form.password.label }}<br>
                {% if login_form.password.errors %}
                    {{ login_form.password(**{"type":"password", "class":"form-control is-invalid", "id":"inputEmail", "placeholder":"Password","data-validator-label":"Password", "data-validator":"required|min:4|max:10"}) }}
                    <div class="form-control-feedback invalid-feedback">
                        {% for error in login_form.password.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                {% else %}
                    {{ login_form.password(**{"type":"password", "class":"form-control", "id":"inputEmail", "placeholder":"Password","data-validator-label":"Password", "data-validator":"required|min:4|max:10"}) }}
                    <div class="form-control-feedback"></div>
                {% endif %}
            </div>
            <div class="form-check mb-2 mr-sm-2">
                {{ login_form.remember_me(class="form-check-input") }}
                {{ login_form.remember_me.label(class_="form-check-label") }}
            </div>
            <p>New User? <a href="{{ url_for('user_bp.signup') }}">Click to Register!</a></p>
        
            <hr>
            <div class="row justify-content-between spaceUp borderUp">
                <div class="col col-auto mr-auto">
                    <p>{{ login_form.submit(class_='btn btn-primary') }}</p>  
                </div>
                <div class="col col-auto">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

app/app/user/templates/new_login_email.html
{% extends "master.html" %}

{% block main %}
    <h1>Account Verification</h1>
    <p>Dear {{name}},</p>
    <p>In order to secure your account, please use the code below.</p>
    <p>Your unique code is <strong>{{code}}</strong></p>
    <p>Remember your code expires in 5 minutes!</p>
{% endblock %}

app/app/user/templates/payment.html
{% extends "master.html" %}

{% from "macros.html" import payment_details %}

{% block main %}
    <div class="container">
        <div class="jumbotron">
            <h1 class="display-4">Payment #{{ payment.id }}</h1>

            <p class="lead">{{ payment.description }}</p>
        </div>

        <h3>Payment Details</h3>

        {{ payment_details(payment) }}

        <h3>Payment Receipt</h3>

        <a class="btn btn-primary" role="button" aria-pressed="true" href="{{ url_for("user_bp.payment_receipt", payment_id = payment.id) }}">View Receipt</a>
        
    </div>
{% endblock %}

app/app/user/templates/payments.html
{% extends "master.html" %}

{% block main %}
    <div class="container">
        <div class="jumbotron">
            <h1 class="display-4">My Payments</h1>
        </div>

        {% if payments == [] %}
            <p>You've never made any payments.</p>
        {% else %}
        <ul id="paymentsList" style="padding: 0; list-style-type: none;">

            {% for payment in payments %}
                <li style="margin-bottom: 10px;">

                    <div class="card">
                        <div class="card-body row align-items-center">
                            <div class="col">
                                <p class="card-text">{{ payment.description }} - £{{ "%.2f" % payment.get_price_decimal() }} [{{ payment.time.strftime("%d %b %Y at %H:%M") }}]</p>
                            </div>
                            <div class="col-sm-auto">
                                <a class="btn btn-outline-primary" role="button" aria-pressed="true" href="{{ url_for("user_bp.payment_receipt", payment_id = payment.id) }}">View Receipt</a>
                            </div>
                            <div class="col-sm-auto">
                                <a class="btn btn-primary" role="button" aria-pressed="true" href="{{ url_for("user_bp.payment", payment_id = payment.id) }}">View Payment</a>
                            </div>
                        </div>
                    </div>

                </li>
            {% endfor %}

        </ul>
        {% endif %}
    </div>
{% endblock %}

app/app/user/templates/signup.html
{% extends "user.html" %} 



{% block userCont %}
    <h1>Signup</h1>
    <div class="container-fluid" id="formErrors">
        {% for fieldName, errorMessages in form.errors.items() %}
            {% for err in errorMessages %}
                <div class="alert alert-danger alert-dismissable show" role="alert">
                    {{fieldName}}:{{err}}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
            
                </div>
            {% endfor %}
        {% endfor %}
    </div>

    <div class="container">
        <form method="POST" action="{{url_for('user_bp.signup')}}">
            {{ form.hidden_tag() }}
            <div class="form-group">
                <div class="form-row">
                    <div class="col">
                        {{ form.first_name(class_="form-control", id="firstName", placeholder="First Name")}}
                    </div>
                    <div class="col">
                        {{ form.last_name(class_="form-control", id="lastName", placeholder="Last Name")}}
                    </div>
                </div>
            </div>
            <div class="form-group">
                {{ form.email(class_="form-control", id="email", placeholder="Email")}}
            </div>
            <div class="form-group">
                {{ form.password(class_="form-control", id="password", placeholder="Password")}}
            </div>
            <div class="form-group">
                {{ form.emergency_number(class_="form-control", id="iceNumber", placeholder="Emergency Phone Number")}}
            </div>
            <div class="form-group">
                {{ form.dob(class_="form-control", id="dob")}}
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Signup</button><br>
                <small>By signing up you are agreeing to our
                    <a href="{{url_for('user_bp.privacy_policy')}}" target="_blank">privacy policy</a>.
                </small>
            </div>
        </form>
    </div>
{% endblock %}

app/app/user/templates/user.html
{% extends "master.html" %}

{% block main %}
    {% block userCont %}
    {% endblock %}
{% endblock %}

{% block scripts %}
    <script type="text/javascript" src="{{ url_for('.static', filename='user.js') }}"></script>
{% endblock %}